# Generated by Django 4.1.3 on 2022-11-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(default=1, upload_to='media', verbose_name='Car image'),
            preserve_default=False,
        ),
    ]
