# Generated by Django 4.1.3 on 2022-11-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40, verbose_name='Phone')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('adres', models.CharField(max_length=40, verbose_name='adres')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
            },
        ),
    ]
